/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVehiculosRouteImport } from './routes/_app.vehiculos'
import { Route as AppReportesRouteImport } from './routes/_app.reportes'
import { Route as AppHistorialRouteImport } from './routes/_app.historial'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConfiguracionRouteImport } from './routes/_app.configuracion'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiculosRoute = AppVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorialRoute = AppHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/historial': typeof AppHistorialRoute
  '/reportes': typeof AppReportesRoute
  '/vehiculos': typeof AppVehiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracion': typeof AppConfiguracionRoute
  '/dashboard': typeof AppDashboardRoute
  '/historial': typeof AppHistorialRoute
  '/reportes': typeof AppReportesRoute
  '/vehiculos': typeof AppVehiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/configuracion': typeof AppConfiguracionRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/historial': typeof AppHistorialRoute
  '/_app/reportes': typeof AppReportesRoute
  '/_app/vehiculos': typeof AppVehiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/dashboard'
    | '/historial'
    | '/reportes'
    | '/vehiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracion'
    | '/dashboard'
    | '/historial'
    | '/reportes'
    | '/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/configuracion'
    | '/_app/dashboard'
    | '/_app/historial'
    | '/_app/reportes'
    | '/_app/vehiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehiculos': {
      id: '/_app/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof AppVehiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes': {
      id: '/_app/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historial': {
      id: '/_app/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AppHistorialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHistorialRoute: typeof AppHistorialRoute
  AppReportesRoute: typeof AppReportesRoute
  AppVehiculosRoute: typeof AppVehiculosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHistorialRoute: AppHistorialRoute,
  AppReportesRoute: AppReportesRoute,
  AppVehiculosRoute: AppVehiculosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
